# Generated by Django 4.2.4 on 2023-08-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_remove_thread_image_imagethread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagethread',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_thread', to='thread.thread'),
        ),
    ]
