# Generated by Django 4.2.4 on 2023-08-20 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0007_rename_rethread_count_thread_comment_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rethread',
            new_name='Repost',
        ),
        migrations.RenameModel(
            old_name='ImageThread',
            new_name='ThreadImage',
        ),
        migrations.RenameField(
            model_name='recomment',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='recomment',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='thread.thread'),
        ),
        migrations.CreateModel(
            name='RecommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recomment_images/')),
                ('recomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomment_image', to='thread.recomment')),
            ],
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment_images/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_image', to='thread.comment')),
            ],
        ),
    ]
