# Generated by Django 4.2.4 on 2023-08-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0008_rename_rethread_repost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommentimage',
            name='recomment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='thread.comment'),
        ),
        migrations.DeleteModel(
            name='Recomment',
        ),
        migrations.DeleteModel(
            name='RecommentImage',
        ),
    ]
