# Generated by Django 4.2.4 on 2023-08-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0010_alter_comment_options_alter_repost_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='threader',
            new_name='user',
        ),
    ]
