# Generated by Django 4.2.4 on 2023-09-05 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0015_comment_liked_users_thread_liked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='reposted_users',
            field=models.ManyToManyField(blank=True, related_name='reposted_threads', through='thread.Repost', to=settings.AUTH_USER_MODEL),
        ),
    ]
